## Usage test of the wrapper


In [1]:
# imports
import pandas as pd
import numpy as np

import logging

# from wrapper import RustDataModule
from rust_time_series.rust_time_series import (
    BaseDataSet,
    DatasetType,
    ImputeStrategy,
    SplittingStrategy,
)

In [2]:
# set up logging
logging.basicConfig(level=logging.INFO)

In [3]:
# create dummy 2D array
dummy = np.random.randint(0, 100, (100, 10)).astype(float)

# Create a RustTimeSeries instance
dummy_ts = BaseDataSet(dummy, 3, 3, 1)
dummy_ts.set_to_100()


dummy

array([[100.,  55.,  94.,  70.,   1.,  82.,  85.,  31.,   5.,  17.],
       [ 27.,  74.,  34.,  38.,  68.,   3.,   9.,  22.,   1.,  70.],
       [ 11.,   7.,  67.,  44.,   2.,  43.,  25.,  29.,  93.,  57.],
       [ 54.,  90.,  45.,  59.,  45.,   8.,  61.,  38.,  85.,  46.],
       [  4.,  38.,  89.,  45.,  74.,  54.,  27.,  44.,  62.,  29.],
       [ 47.,  44.,  42.,  24.,  23.,  42.,  88.,  68.,  73.,  95.],
       [  2.,  94.,  16.,  87.,  31.,  58.,  56.,  67.,  68.,   6.],
       [ 15.,  78.,   8.,  48.,   2.,  18.,  41.,  91.,  96.,  54.],
       [ 94.,  18.,  19.,  89.,  62.,  72.,   6.,   7.,  60.,  16.],
       [ 73.,  98.,  16.,  49.,  52.,  46.,  70.,   0.,  77.,  67.],
       [ 53.,  85.,  39.,  62.,  16.,  92.,  33.,  49.,   9.,  43.],
       [  2.,  65.,  45.,   1.,  77.,   4.,  85.,  88.,  53.,  37.],
       [ 54.,  65.,  50.,  51.,   6.,  92.,  78.,  63.,  42.,  41.],
       [  5.,   5.,  48.,  47.,  62.,  10.,  94.,  47.,  13.,  36.],
       [ 36.,  62.,  95.,  40.,  6

In [5]:
split = (0.7, 0.2, 0.1)
# confirm that split adds up to 1
# assert sum(split) == 1.0, "Split proportions must sum to 1."

(part1, part2, part3) = dummy_ts.split(SplittingStrategy.Temporal, *split)

print(len(part1), len(part2), len(part3))

70 20 10


### Dummy classification dataset

In [6]:
labels = np.ones((100, 1), dtype=np.float64)
labels = labels.astype(str)
labels_list = labels.flatten().tolist()

dummy_class = BaseDataSet.new_classification(
    dummy, labels_list
)

dummy_class.len()

100

In [7]:
split = (0.7, 0.2, 0.1)
# confirm that split adds up to 1
# assert sum(split) == 1.0, "Split proportions must sum to 1."

(part1, part2, part3) = dummy_class.split(SplittingStrategy.Random, *split)

print(len(part1), len(part2), len(part3))

70 20 10


### Forecasting Dataset

In [8]:
# Load the dataset
file_path = "LD2011_2014.txt"
df = pd.read_csv(file_path, sep=";", decimal=",")
# drop first column (date)
df = df.drop(columns=["date"])
# turn pandas DataFrame into numPy array
data = df.to_numpy(dtype=np.float64)

data

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.53807107e+00, 2.06258890e+01, 1.73761946e+00, ...,
        1.53589316e+02, 6.70087977e+02, 6.86486486e+03],
       [1.26903553e+00, 2.13371266e+01, 1.73761946e+00, ...,
        1.46911519e+02, 6.46627566e+02, 6.54054054e+03],
       [2.53807107e+00, 1.99146515e+01, 1.73761946e+00, ...,
        1.31886477e+02, 6.73020528e+02, 7.13513514e+03]])

In [9]:
ts = BaseDataSet(data, 3, 3, 3)
ts.set_to_100()

print(type(data))
print(data.shape)

<class 'numpy.ndarray'>
(140256, 370)


In [10]:
(part1, part2, part3) = ts.split(SplittingStrategy.Temporal, 0.7, 0.2, 0.1)

len(part1), len(part2), len(part3)

(98179, 28051, 14026)

### Classification Dataset

In [11]:
from aeon.datasets import load_classification
X, y = load_classification("GunPoint")
X = X.reshape(X.shape[0], -1)

print(type(X))
print(X.shape)

<class 'numpy.ndarray'>
(200, 150)


In [12]:
ts = BaseDataSet.new_classification(X, y)

(part1, part2, part3) = ts.split(SplittingStrategy.Random, 0.7, 0.2, 0.1)

len(part1), len(part2), len(part3)

(140, 40, 20)

Usage of RustDataModule


In [13]:
from wrapper import RustDataModule

Rust Time Series Wrapper Loaded


In [14]:
rust_dm = RustDataModule(data, DatasetType.Forecasting, 3, 3, 3)

In [15]:
rust_dm.setup()

In [16]:
train_dl = rust_dm.train_dataloader()

train_dl

In [17]:
# test wether the dataloader works
for batch in train_dl:
    print(batch)
    print(batch.shape)
    break

tensor([[100.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        ...,
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.],
        [  0.,   0.,   0.,  ...,   0.,   0.,   0.]], dtype=torch.float64)
torch.Size([32, 370])
